#pragma once

#define YSH_INPUT_0 SDL_SCANCODE_0
#define YSH_INPUT_1 SDL_SCANCODE_1
#define YSH_INPUT_2 SDL_SCANCODE_2
#define YSH_INPUT_3 SDL_SCANCODE_3
#define YSH_INPUT_4 SDL_SCANCODE_4
#define YSH_INPUT_5 SDL_SCANCODE_5
#define YSH_INPUT_6 SDL_SCANCODE_6
#define YSH_INPUT_7 SDL_SCANCODE_7
#define YSH_INPUT_8 SDL_SCANCODE_8
#define YSH_INPUT_9 SDL_SCANCODE_9

#define YSH_INPUT_A SDL_SCANCODE_A
#define YSH_INPUT_B SDL_SCANCODE_B
#define YSH_INPUT_C SDL_SCANCODE_C
#define YSH_INPUT_D SDL_SCANCODE_D
#define YSH_INPUT_E SDL_SCANCODE_E
#define YSH_INPUT_F SDL_SCANCODE_F
#define YSH_INPUT_G SDL_SCANCODE_G
#define YSH_INPUT_H SDL_SCANCODE_H
#define YSH_INPUT_I SDL_SCANCODE_I
#define YSH_INPUT_J SDL_SCANCODE_J
#define YSH_INPUT_K SDL_SCANCODE_K
#define YSH_INPUT_L SDL_SCANCODE_L
#define YSH_INPUT_M SDL_SCANCODE_M
#define YSH_INPUT_N SDL_SCANCODE_N
#define YSH_INPUT_O SDL_SCANCODE_O
#define YSH_INPUT_P SDL_SCANCODE_P
#define YSH_INPUT_Q SDL_SCANCODE_Q
#define YSH_INPUT_R SDL_SCANCODE_R
#define YSH_INPUT_S SDL_SCANCODE_S
#define YSH_INPUT_T SDL_SCANCODE_T
#define YSH_INPUT_U SDL_SCANCODE_U
#define YSH_INPUT_V SDL_SCANCODE_V
#define YSH_INPUT_W SDL_SCANCODE_W
#define YSH_INPUT_X SDL_SCANCODE_X
#define YSH_INPUT_Y SDL_SCANCODE_Y
#define YSH_INPUT_Z SDL_SCANCODE_Z

#define YSH_INPUT_LSHIFT SDL_SCANCODE_LSHIFT
#define YSH_INPUT_LCTRL SDL_SCANCODE_LCTRL
#define YSH_INPUT_SPACE SDL_SCANCODE_SPACE

#define YSH_INPUT_LMOUSEBUTTON 256
#define YSH_INPUT_RMOUSEBUTTON 257

bool IsKeyboardInput(unsigned short ysh_input_code);